### PR TITLE
feat: button to remove a movie from Radarr/Sonarr

### PR DESCRIPTION
**Pull request by dd060606**
#### Description
Added button in ManageSlideOver to remove movie and media file from Radarr/Sonarr
#### Screenshot (if UI-related)
image

#### To-Dos

- [x] Successful build `yarn build`
- [x] Translation keys `yarn i18n:extract`
- [ ] Database migration (if required)

(Sorry for my English, I'm French)

### CODE REVIEW

**Comment by Fallenbagel** [comment]
I was wondering wouldn't it be better to hide that button when default service is not configured as opposed to throwing the error to log? (This might reduce some confusion in users + another dev also suggested the same)

**Comment by dd060606** [comment]
> I was wondering wouldn't it be better to hide that button when default service is not configured as opposed to throwing the error to log? (This might reduce some confusion in users + another dev also suggested the same)

Yes it's a good idea. I will fix this as soon as possible.

**Comment by dd060606** [comment]
> I was wondering wouldn't it be better to hide that button when default service is not configured as opposed to throwing the error to log? (This might reduce some confusion in users + another dev also suggested the same)

After checking, there is already a condition to check if the service URL is not null
```typescript
{hasPermission(Permission.ADMIN) &&
    data?.mediaInfo?.serviceUrl && (
```
And when I remove the default service, the button doesn't appear
image

Was your question about that?

**Comment by Fallenbagel** [comment]
> Was your question about that?

Yes it was. I wonder why the button appeared on mine. I'll test again tonight and if all's good will merge

**Comment by Fallenbagel** [comment]
@dd060606 Hi. Sorry took a while to test but from my testing when I have the default service not selected i can still see the button

image

image

**Comment by dd060606** [comment]
> @dd060606 Hi. Sorry took a while to test but from my testing when I have the default service not selected i can still see the button
> 
> image
> 
> image
> 

Ok I will fix this as soon as possible 👍

**Comment by Fallenbagel** [comment]
@dd060606 Could you resolve the merge conflict? Once done could deploy this for testing

**Comment by dd060606** [comment]
@Fallenbagel ok I will fix this as soon as possible 👍

**Comment by dd060606** [comment]
@Fallenbagel I solved the merge conflict

**Comment by Fallenbagel** [comment]
Hi could you fix the lint issues?

**Comment by dd060606** [comment]
> Hi could you fix the lint issues?

Yes I will fix that 👍

**Comment by dd060606** [comment]
@Fallenbagel I think I solved the conflict.

**Comment by Fallenbagel** [comment]
Thanksss

**Comment by Fallenbagel** [comment]
I've tested this a lot, and I have not had any issues. I think we're good to merge soon!

**Comment by markv9401** [comment]
Any updates on the state of this long on-going / due merge? It'd be very welcome!

Also, in my opinion deleting media should be a single process too, like "delete from Radarr" => deletes from Radarr, including the files and clears all data from within Jellyseer too. Is clearing from Jellyseer included in this function?

**Comment by dd060606** [comment]
> Any updates on the state of this long on-going / due merge? It'd be very welcome!
> 
> Also, in my opinion deleting media should be a single process too, like "delete from Radarr" => deletes from Radarr, including the files and clears all data from within Jellyseer too. Is clearing from Jellyseer included in this function?

The "delete from Radarr" button already removes all data on the movie including all files and clears all data from Jellyseerr

**Comment by Fallenbagel** [comment]
> Any updates on the state of this long on-going / due merge? It'd be very welcome!

I'm currently deploying this as `preview-pr182` for testing purposes. It should be built in about 1-2hrs depending on how fast github actions does it

**Comment by Uruknara** [comment]
when merging to master ? @Fallenbagel

**Comment by Fallenbagel** [comment]
> when merging to master ? @Fallenbagel 

I am looking to merging this to master along with OIDC this week. I'll merge this one as soon as the merge conflicts are taken care of

**Comment by dd060606** [comment]
> > when merging to master ? @Fallenbagel
> 
> I am looking to merging this to master along with OIDC this week. I'll merge this one as soon as the merge conflicts are taken care of
> 
> @dd060606 sorry for the loooong delay on this PR as this is kind of a big feature but I am ready to merge ASAP c:

@Fallenbagel I solved the merge conflict 👍

**Comment by Fallenbagel** [comment]
@dd060606 could you run prettier on the manageSlideOver?

**Comment by dd060606** [comment]
> @dd060606 could you run prettier on the manageSlideOver file?

@Fallenbagel I think I solved the code style issues

**Review by Fallenbagel — APPROVED** [review]

**Comment by Fallenbagel** [comment]
@dd060606 Is the button always supposed to show or only when media is available? Just making sure if it was the intended behavior or not (a question on discord by a user)

**Comment by dd060606** [comment]
> @dd060606 Is the button always supposed to show or only when media is available? Just making sure if it was the intended behavior or not (a question on discord by a user)

The button is supposed to show when the movie is detected in Radarr or Sonarr but it doesn't check if the movie is available or not (like the "open in Radarr" button)

**Comment by Fallenbagel** [comment]
> The button is supposed to show when the movie is detected in Radarr or Sonarr but it doesn't check if the movie is available or not (like the "open in Radarr" button)

According to them, it is always showing despite the media being absent on *arr. I haven't tested it myself but currently I am updating to test it. Would edit this comment after testing

**Comment by Fallenbagel** [comment]
@all-contributors please add @dd060606 for code

**Pull request merged**
