### PR TITLE
fix: resolve error when setup on second attempt

### PR DESCRIPTION
**Pull request by gauthier-th**
#### Description

This PR fixes a bug where the setup process was stuck if any error occurred after the first setup.
Instead of just checking if an admin user exists in database, this PR will also check if the settings are properly set up, and if so edit the admin user according to the new settings provided during the 2nd setup.

Steps to reproduce:
- Do the whole setup process
- Stop Jellyseerr
- Delete settings.json
- The setup page appears again but you can't setup Jellyseerr anymore.

#### To-Dos

- [x] Successful build `pnpm build`
- [ ] Translation keys `pnpm i18n:extract`
- [ ] Database migration (if required)

#### Issues Fixed or Closed

- Fixes #XXXX

### CODE REVIEW

**Review by Fallenbagel — CHANGES_REQUESTED** [review]
Please add more details of what this PR achieves to solve

**Comment by gauthier-th** [comment]
> Please add more details of what this PR achieves to solve

Done

**Review by Fallenbagel — APPROVED** [review]
LGTM!

**Pull request merged**
