### PR TITLE
Update Spanish translations

### PR DESCRIPTION
**Pull request by CheChu10**
#### Description
- Added some missing Spanish translations and fixed a spelling mistake. 
- Ordered by JSON Keys.

#### Screenshot (if UI-related)
Not an UI update.

#### To-Dos

- [x] Successful build `yarn build`
- [ ] Translation keys `yarn i18n:extract`
- [ ] Database migration (if required)

#### Issues Fixed or Closed
None

### CODE REVIEW

**Comment by Fallenbagel** [comment]
Could you fix the formatting issue? Needs prettier to be run on the `es.json` file

**Comment by CheChu10** [comment]
> Could you fix the formatting issue? Needs prettier to be run on the `es.json` file

Yes. Sorry friend, I did. Make changes from github edit not good idea :P . I cloned project and configure with my PHPStorm ^^.

Sorry for the inconvenience. I will try to add more translations and help more actively to project.

**Comment by Fallenbagel** [comment]
> Sorry for the inconvenience. I will try to add more translations and help more actively to project.

It's okay no need to apologise c:
Thank you so much for the work!

**Review by Fallenbagel — APPROVED** [review]

**Comment by Fallenbagel** [comment]
@all-contributors please add @CheChu10 for translation

**Pull request merged**
