### PR TITLE
Update action

### PR DESCRIPTION
**Pull request by Gauvino**
- Update action version to latest (remove all warnings)
 - Update nodejs version on action
 - Update ubuntu to latest on support action

### CODE REVIEW

**Comment by Fallenbagel** [comment]
Oh shit I've been building the release on node version 16 huh

**Comment by Gauvino** [comment]
> Oh shit I've been building the release on node version 16 huh

That's why i made the PR but also for the workflow using 1year old action version

Just wait until every build check is complete and if so you can merge it without problem I think and if their is a problem i'll fix it instantly

**Comment by Gauvino** [comment]
good to go !

**Review by Fallenbagel — APPROVED** [review]

**Pull request merged**
