### PR TITLE
Fix overseerr-api.yml

### PR DESCRIPTION
**Pull request by Kara-Zor-El**
#### Description
- fixes errors in `overseerr-api.yml`

### CODE REVIEW

**Review by Fallenbagel — CHANGES_REQUESTED** [review]
Could you update the commit message to use a conventional commit message specification please?

**Comment by Kara-Zor-El** [comment]
:+1: changed commit message

**Review by Fallenbagel — APPROVED** [review]

**Comment by Fallenbagel** [comment]
@all-contributors please add @Kara-Zor-El for infra

**Comment by Fallenbagel** [comment]
@all-contributors please add @Kara-Zor-El for infra

**Pull request merged**
