### PR TITLE
feat: add Lidarr and MusicBrainz support

### PR DESCRIPTION
**Pull request by Svagtlys**
This PR aims to add Lidarr and MusicBrainz support to Jellyseerr to address feature request #96 

I'm pretty new to this kind of coding, so I'm mostly just making changes, running a build, and fixing bugs as they come up. I'm using https://github.com/sct/overseerr/pull/3800 by @anon0002 as a guide/code source for the heftier bits like the Lidarr API classes.

In feature request #96 @zachbakerdev mentioned using Deezer instead of MusicBrainz as it has more info on covers, but I'm not sure that Lidarr supports that and I've not interacted with Deezer before, so I'm currently sticking with MusicBrainz. I'm happy to also add Deezer support at some point in the future.

### CODE REVIEW

**Comment by zachbakerdev** [comment]
One of the other considerations I had was instead of using the cover art archive that Musicbrainz uses was searching on Musicbrainz for the albums, then mapping those albums to Deezer instead of the other way around. Just a consideration.

**Comment by ano0002** [comment]
It seems like you forgot to add the type definitions I had to add so it will not work I think.
[I'm talking about this](https://github.com/ano0002/overseerr/blob/overseer-with-lidarr-support/server/types/nodebrainz.d.ts)
But since I don't know how jellyseer is setup you might not need it

**Comment by Svagtlys** [comment]
@ano0002 I actually had a few questions about your implementation of the nodebrainz API, for example why didn't you copy the interfaces of TMDB with all of the Result interfaces?

I haven't added all of your work into this PR (yet) as I'm trying to learn a bit about Typescript/Javascript and how different people code as I'm doing this :D I'll admit I also don't have a deep understanding of how Jellyseerr functions so I'm trying to learn that as well to determine which nodebrainz features are needed.

**Comment by ano0002** [comment]
> @ano0002 I actually had a few questions about your implementation of the nodebrainz API, for example why didn't you copy the interfaces of TMDB with all of the Result interfaces?
> 
> I haven't added all of your work into this PR (yet) as I'm trying to learn a bit about Typescript/Javascript and how different people code as I'm doing this :D I'll admit I also don't have a deep understanding of how Jellyseerr functions so I'm trying to learn that as well to determine which nodebrainz features are needed.

I'll try to answer all those question when I get some time as right now I have all my final exams.

**Comment by ano0002** [comment]
> @ano0002 I actually had a few questions about your implementation of the nodebrainz API, for example why didn't you copy the interfaces of TMDB with all of the Result interfaces?
> 
> I haven't added all of your work into this PR (yet) as I'm trying to learn a bit about Typescript/Javascript and how different people code as I'm doing this :D I'll admit I also don't have a deep understanding of how Jellyseerr functions so I'm trying to learn that as well to determine which nodebrainz features are needed.

I didn't copy them because I didn't want to send the same kind of info. I could have reused it and modified it to take more parameters but that would have meant I'd have to rewrite every other time when the interface was already used so I chose to make a separate one.

**Pull request closed without merging**
