### PR TITLE
feat: Custom jellyfin password reset setting

### LINKED ISSUE #212: Remove Jellyfin Password Reset
### Description

When Reset Password is clicked, Jellyseerr redirects user to LAN IP and Port for Jellyfin.

### Desired Behavior

Remove Option. User should reset password from Jellyfin UI.

### Additional Context

Docker
Bridged Network
Reverse Proxy

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

### PR DESCRIPTION
**Pull request by notquitenothing**
#### Description
Adding Jellyfin Setting for Custom "Forgot Password" URL.  Useful in cases where you are using a custom authentication provider such as the Jellyfin LDAP plugin with Authelia. Authentik, lldap, or any other external auth scheme with its own password reset page.

I came across this idea in https://github.com/Fallenbagel/jellyseerr/issues/212#issuecomment-1699893393 , so thanks @Hani-K.
Even though this issue is marked as fixed, it didn't resolve my issue using Authelia to manage LDAP users through Jellyfin, where Jellyfin's password reset page doesn't work. Backwards compatible against existing settings files, and no change in existing password reset functionality if the setting is blank.

#### Screenshot (if UI-related)

image

#### To-Dos

- [x] Successful build `yarn build`

#### Issues Fixed or Closed

- Fixes #212

### CODE REVIEW

**Comment by Fallenbagel** [comment]
Shouldn't this go when #184 is merged. Currently in develop it will go to external domain

**Comment by Fallenbagel** [comment]
Oh wait this is for LDAP users right?

**Comment by notquitenothing** [comment]
Yep, that other OIDC PR looks cool, but my use case is much simpler. This just lets me redirect users to my Authelia password reset page (which can send a password reset email for my LDAP users) instead of the non-functional Jellyfin password reset page. On the Jellyfin side I use custom CSS to hide the “Reset Password” option and provide password reset link to Authelia.

**Review by Fallenbagel — APPROVED** [review]

**Pull request merged**
