### PR TITLE
feat(job): media availability support for jellyfin/emby

### LINKED ISSUE #84: [Feature Request] Automatically purge media that has been deleted from jellyfin
#### Description

Previously available, but now deleted movies from Jellyfin still shows as available in Jellyseer. You have to manually use option on Jellyseer to delete all data to remove that status. This bug messes up requests, for example I've seen said movie, deleted it, but someone else wants to see it after some time, it shows on Jellyseer as avalable, presses "Play on Jellyfin", it attempts to open the link and it hangs on Jellyfin loading screen. And while it shows as available, it's not possible to request it again. Admin needs to manually clear data for that movie.

#### Version

Jellyseer v1.0.2, docker image
Jellyfin v10.7.7, official docker image

#### Steps to Reproduce

Set up Jellyseer with Jellyfin.
Movies synced, available movies on your Jellyfin show up as Available on Jellyseer.
1. Delete movie on Jellyfin
2. That same movie still shows up on Jellyseer as available.

#### Expected Behavior

Previously available and now deleted movie on Jellyfin, is not available on Jellyseer and users can request it again.

#### Screenshots

not necessary. 

#### Device

-all devices

### LINKED ISSUE #193: Availability of media doesn't change after a full scan.
### Description

After deleting media in Jellyfin, Jellyseerr still marks the media as Available. So you can't request it a 2nd time.
Even when running a manual Full Library scan it still marks it as Available.

### Version

1.1

### Steps to Reproduce

1. Request media in Jellyseerr.
2. Delete it from Sonarr/Radarr/Jellyfin.
3. Notice that Jellyfin doesn't show the movie anymore in the library.
4. Do a Full Manual Library Scan in Jellyseerr.

### Screenshots

msedge_ONI1ipu3kS

All this media has been deleted from my server already, jellyseerr marks it as Available.

### Logs

_No response_

### Platform

desktop

### Device

Windows

### Operating System

Ubuntu

### Browser

Edge

### Additional Context

_No response_

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

### LINKED ISSUE #362: [Feature Request] Clear request status when media is not found in library
### Description

If it is not too much trouble I wanted to ask if you can add an option to activate the following behaviour:

Sometimes a request gets added, the media will be added into the library but deleted after a short period of time. If I am not mistaken the status of the request stays on "available" no matter if the media was deleted or not. That leads to confusion of users when they see "Media X is available." but they can't find it in Jellyfin, since it got deleted. Would be super nice if there was an option like that.

### Desired Behavior

On a full library scan, clear the request status if the media is not found in the library.

### Additional Context

Thank you for all your work, I've been a fan since day one. Greatly appreciate it! <3

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

### LINKED ISSUE #406: Media availability sync job is broken for jellyfin/emby media servers
### Description

The media availability sync job feature in Jellyseerr only supports Plex Media Server as the backend for checking availability. However, when setting up the app with Jellyfin or Emby as the media server backend, the media availability sync job behaves unpredictably. It sometimes removes requests and availability status from media that is available in Jellyfin/Emby and/or Sonarr/Radarr. It does not remove availability status from removed media.

Currently, jellyseerr has the job [disabled](https://github.com/Fallenbagel/jellyseerr/blob/develop/server/job/schedule.ts#L156-L171) until it can be reworked to support Jellyfin/Emby media server backends.

### Version

Latest

### Steps to Reproduce

1. Remove a media from jellyfin/emby and/or sonarr/radarr
2. Observe availability status not removed by the media availability sync job
3. Once job finishes, observe some existing media on both jellyfin/emby and sonarr/radarr to be set to UNKNOWN and request deleted

### Screenshots

_No response_

### Logs

_No response_

### Platform

desktop

### Device

not relevant

### Operating System

not relevant

### Browser

not relevant

### Additional Context

_No response_

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

### LINKED ISSUE #516: Deleted Movies and shows on Jellyfin still show as available
### Description

So, the issue is that I accidentally deleted a few seasons of a show, and now I need them back. When I search for that show on Jellyseerr, it shows that it is available, but I can't find the show's seasons in my drive. This has also happened with movies. I also scan Jellyfin library from Jellyseerr There are some screenshots down below..

### Version

1.7.0

### Steps to Reproduce

---

### Screenshots

image
image

### Logs

_No response_

### Platform

desktop

### Device

Any

### Operating System

Linux

### Browser

Same of all browser

### Additional Context

_No response_

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

### PR DESCRIPTION
**Pull request by fallenbagel**
#### Description
This refactors the media availability job to support jellyfin/emby for media removal automatically.
Needs further testing on 4k items (as I have not yet tested with 4k), however, non-4k items work as
intended.

#### Screenshot (if UI-related)
image

#### To-Dos

- [x] Successful build `yarn build`
- [x] Translation keys `yarn i18n:extract`
- [x] Test with 4k items
- [x] Test against plex

#### Issues Fixed or Closed

- Fixes #406 
- Fixes #193 
- Fixes #516 
- Fixes #362 
- Fixes #84

### CODE REVIEW

**Comment by alexboutros** [comment]
Is this just waiting on a test with 4k items?

**Comment by Fallenbagel** [comment]
> Is this just waiting on a test with 4k items?

Actually yes

**Comment by alexboutros** [comment]
> > Is this just waiting on a test with 4k items?
> 
> Actually yes and no.
> 
> Yes i want 4k items to be tested before i merge but no I might merge this, this week nevertheless

Gotcha. I just spun up jellyfin locally, I may give testing 4K items a go myself if that'd be any help.

**Comment by Fallenbagel** [comment]
> Gotcha. I just spun up jellyseerr locally, I may give testing 4K items a go myself if that'd be any help.

That would help a lot yes 🙏

**Comment by alexboutros** [comment]
@Fallenbagel I just finished putting together my local set up. Sabnzbd/sonarr/radarr/jellyfin and running jellyseerr out of the -feat-media-availability branch.

Requested a 4K movie through jellyseerr, it went into Radarr, then into SABnzbd successfully. Jellyseerr picked it up and showed it as available. Deleted the movie file out of the folder (unmonitored in Radarr), ran media availability scan in Jellyseer, and it updated the movie to show it as available for requesting.

Repeated the process for a movie again, same result. 

Did the same thing for two 4K episodes of a show. Deleted on episode, ran the scan, Jellyseerr still showed as partially available. Deleted the second episode and ran the scan, and jellyseerr removed the "partially available" flag and showed it as requestable.

Looks like the media availability scan is working perfectly for me.

Any logs or anything you'd like?

**Comment by Fallenbagel** [comment]
Woah nice. Dont need logs if its working well. Didnt even expect that it'd work well becausd when i was developing, i had no ways of testing and was too lazy to setup test *arrs and stuff. 

Thank you so much for testing!

**Comment by alexboutros** [comment]
> Woah nice. Dont need logs if its working well. Didnt even expect that it'd work well becausd when i was developing, i had no ways of testing and was too lazy to setup test *arrs and stuff.
> 
> Thank you so much for testing!

My pleasure. I've been meaning to set up my local arrs and everything because there's a small feature I'd like to contribute to jellyseerr. Going through the contribution docs now :)

**Comment by Noah-Huppert** [comment]
I just tested this out on my Overseerr setup (no 4k media) and it worked great! Thank you!

**Review by apb-hello-world — APPROVED** [review]
LGTM. Tested successfully.

**Comment by David-Moreira** [comment]
Hello @Fallenbagel 
Can I ask what's the expected ETA for a next release with this PR? 

Thanks!

**Comment by Fallenbagel** [comment]
> Hello @Fallenbagel 
> Can I ask what's the expected ETA for a next release with this PR? 
> 
> Thanks!

I want to merge this asap. As for the release, as snap builds are broken, I'm contemplating whether to release after fixing it or skip snap builds for next version

**Comment by David-Moreira** [comment]
Well, in my opinion, it would be best/correct to release in every platform you usually do if you do plan on keeping on supporting all of those. 
So in that case, In my personal opinion, 
after fixing snap build **OR** if possible, manually releasing if fixing the automatic build is too time consuming / too much trouble?

In my case I'm using a docker image so I personally don't really care about it.
Keep up the good work, Cheers.

**Comment by Fallenbagel** [comment]
I need this pr to be tested against a plex server

**Comment by Panda260** [comment]
> I need this pr to be tested against a plex server

@Fallenbagel  I tested it with Jellyseer, Plex and Jellyfin and it seems to be working fine.

**Comment by Fallenbagel** [comment]
> > I need this pr to be tested against a plex server
> 
> @Fallenbagel  I tested it with Jellyseer, Plex and Jellyfin and it seems to be working fine.
> 

On plex, did you test removal of shows, movies, and also if after running the job, any shows that weren't deleted had their seasons correctly marked as available (as in it didn't remove anything it shouldn't?)

**Comment by Panda260** [comment]
OK, it doesn't really work. If I remove a season from a TV show, the entire series is still marked as "Partially Available" but for the individual seasons, nothing can be seen with "Partially Available" or "Available" - the green boxes disappear but after a library scan they are back

**Comment by Fallenbagel** [comment]
> OK, it doesn't really work. If I remove a season from a TV show, the entire series is still marked as "Partially Available" but for the individual seasons, nothing can be seen with "Partially Available" or "Available" - the green boxes disappear but after a library scan they are back

Yeah I think I messed up the season updater for just plex. Thanks! I'll look into it

**Review by ldoctoru — APPROVED** [review]

**Comment by Fallenbagel** [comment]
> for me is working

Jellyfin? Plex?

**Review by ldoctoru — APPROVED** [review]

**Comment by ldoctoru** [comment]
> > for me is working
> 
> Jellyfin? Plex?

Jellyfin

**Comment by mvenus2** [comment]
Any news on this?

**Comment by Panda260** [comment]
I thought the PR was ready and could be merged, why hasn't it been done yet?

**Comment by Fallenbagel** [comment]
> I thought the PR was ready and could be merged, why hasn't it been done yet?

It's not ready. Remember, this pr broke plex. Until this fixed

**Comment by Toixinhell** [comment]
I really hope this feature can be released soon. After deleting a old bad quality collection, it is a shame that it does not remove the collection from jellyseerr.

**Comment by JamsRepos** [comment]
@Fallenbagel What's the status on this?

**Comment by JamsRepos** [comment]
Thanking you! ❤️

**Comment by Noah-Huppert** [comment]
Awesome work!

**Comment by Arkindor** [comment]
Thanks ! Good work !

**Comment by felixschndr** [comment]
I was wondering if there is a release on the horizon (as the last one is quite old with 7 months)? I'd like to use this feature as well but am unsure how to deploy this (using Docker). Any ideas other than manually editing the source code inside the container?

**Comment by Noah-Huppert** [comment]
> I was wondering if there is a release on the horizon (as the last one is quite old with 7 months)? I'd like to use this feature as well but am unsure how to deploy this (using Docker). Any ideas other than manually editing the source code inside the container?

I've been building Docker images off this PR's branch and more recently the develop branch so that I can use this feature:  

[`noahhuppert/jellyseerr:feat-media-availability-sync-emby-jellyfin-support-3@sha256:577c2f68e4fca4ede0667b4ffde0fb52ea6253d55bf831dac7366677a85b7e21`](https://hub.docker.com/layers/noahhuppert/jellyseerr/feat-media-availability-sync-emby-jellyfin-support-3/images/sha256-577c2f68e4fca4ede0667b4ffde0fb52ea6253d55bf831dac7366677a85b7e21?context=repo)  

Stability isn't guaranteed but anecdotally it's been working well for me.

**Comment by Fallenbagel** [comment]
> > I was wondering if there is a release on the horizon (as the last one is quite old with 7 months)? I'd like to use this feature as well but am unsure how to deploy this (using Docker). Any ideas other than manually editing the source code inside the container?
> 
> I've been building Docker images off this PR's branch and more recently the develop branch so that I can use this feature:  
> 
> [`noahhuppert/jellyseerr:feat-media-availability-sync-emby-jellyfin-support-3@sha256:577c2f68e4fca4ede0667b4ffde0fb52ea6253d55bf831dac7366677a85b7e21`](https://hub.docker.com/layers/noahhuppert/jellyseerr/feat-media-availability-sync-emby-jellyfin-support-3/images/sha256-577c2f68e4fca4ede0667b4ffde0fb52ea6253d55bf831dac7366677a85b7e21?context=repo)  
> 
> Stability isn't guaranteed but anecdotally it's been working well for me.

You don't need to do that, though. This pr is available in `develop` tag...

**Comment by Noah-Huppert** [comment]
> > > I was wondering if there is a release on the horizon (as the last one is quite old with 7 months)? I'd like to use this feature as well but am unsure how to deploy this (using Docker). Any ideas other than manually editing the source code inside the container?
> > 
> > 
> > I've been building Docker images off this PR's branch and more recently the develop branch so that I can use this feature:
> > [`noahhuppert/jellyseerr:feat-media-availability-sync-emby-jellyfin-support-3@sha256:577c2f68e4fca4ede0667b4ffde0fb52ea6253d55bf831dac7366677a85b7e21`](https://hub.docker.com/layers/noahhuppert/jellyseerr/feat-media-availability-sync-emby-jellyfin-support-3/images/sha256-577c2f68e4fca4ede0667b4ffde0fb52ea6253d55bf831dac7366677a85b7e21?context=repo)
> > Stability isn't guaranteed but anecdotally it's been working well for me.
> 
> You don't need to do that, though. This pr is available in `develop` tag...

Oh true that image was mainly for when it wasn't merged but now ... 🤦🏻

**Pull request merged**
