### PR TITLE
feat: allow request managers to delete data from sonarr/radarr

### PR DESCRIPTION
**Pull request by xabufr**
#### Description

Allow users who have the `MANAGE_REQUESTS` right to delete media files.
I've done that on the request list to have a quick access to this feature.

This doesn't need to change the API because the API already only requires `MANAGE_REQUESTS` for this call.

#### Screenshot (if UI-related)

image

#### To-Dos

- [x] Successful build `yarn build`
- [x] Translation keys `yarn i18n:extract`
- [ ] Database migration (if required)

#### Issues Fixed or Closed

Related to:
 - https://github.com/Fallenbagel/jellyseerr/issues/393

### CODE REVIEW

**Comment by Panda260** [comment]
oh very cool. very nice idea

**Comment by Panda260** [comment]
@xabufr who can request a deleting?
Only that person who also requested that same movie/tv show?

**Comment by xabufr** [comment]
Any person with the `MANAGE_REQUESTS` can delete any movie/tv show.

**Comment by Panda260** [comment]
Wouldn't it be better if everyone could delete their own requested movie or TV shows just as a suggestion

**Comment by xabufr** [comment]
> > Any person with the `MANAGE_REQUESTS` can delete any movie/tv show.
> 
> So now a user who has permission could simply delete the requested film from every other user? when he has the rights for that?

Yes, any user that can 'manage requests' can delete any request. That was already the case, this PR just add a button to allow the user to also delete request's data, but it don't modify necessary rights.

> Wouldn't it be better if everyone could delete their own requested movie or TV shows just as a suggestion

There is currently no permission to delete you own requests I think, this would require more work, I did this PR as a quick/easy new feature.

**Review by Gauvino — APPROVED** [review]
Tested and works like a charm, just remove the renaming change on en.json (overseerr to jellyseerr) and the change on fr.json causing weblate trouble please

**Comment by xabufr** [comment]
@Gauvino I removed the bad commit for the en.json file, but for the new translation keys where  should I put them?

**Comment by Gauvino** [comment]
> @Gauvino I removed the bad commit for the en.json file, but for the new translation keys where  should I put them?

You just keep the translation keys on the en.json, remove the change in fr.json

**Comment by xabufr** [comment]
done !

**Comment by xabufr** [comment]
@Fallenbagel is it good for you?

**Comment by Gauvino** [comment]
Could you refactor this to make it work with the new fetch api please ?

**Review by gauthier-th — CHANGES_REQUESTED** [review]
Please update your PR to use the Fetch API instead of Axios.

**Comment by Gauvino** [comment]
@xabufr don't know if you missed, but please could you update and use the fetch API? Thanks!

**Comment by xabufr** [comment]
Yes sorry I completely forget this issue, I'll try to do it this week

**Comment by xabufr** [comment]
@Gauvino I've made requested changes about `fetch` API

**Review by gauthier-th — APPROVED** [review]

**Review by Fallenbagel — APPROVED** [review]

**Comment by Gauvino** [comment]
Tested and works as expected!

**Comment by lazi3b0y** [comment]
So how is this suppose to work? 
I've given Manage Requests permissions to a user but that user can only remove the request, not delete anything from Radarr or Sonarr. 
But if I give the user Admin permissions I'm able to remove stuff from Radarr and Sonarr.

**Comment by holzerseb** [comment]
Not sure if this is the desired behaviour or a bug - but this new feature to remove media from sonarr/radarr is only available through the request page. When one navigates to the media page itself and clicks on "Manage Movie" the window shows only the option to delete the request, and afterwards is completely empty:
Screenshot 2024-12-08 at 17 54 42

Only users with the "Admin" permission can see the option to remove the media:
Screenshot 2024-12-08 at 17 54 22

Is this the desired effect or am I missing something @gauthier-th ? Thank you so much for the project!

**Comment by gauthier-th** [comment]
> Not sure if this is the desired behaviour or a bug - but this new feature to remove media from sonarr/radarr is only available through the request page.

This is the desired behavior.

> Only users with the "Admin" permission can see the option to remove the media:

I can't reproduce this issue. Is there anything specific you did to have this issue?
Here is the view of a user with the Manage Request permission on the latest version:

image

In any case, I don't think it has anything to do with this issue. This issue only adds the "Delete from *arr" button in the request list.

**Pull request merged**
