### PR TITLE
Fix translation on fr.json

### PR DESCRIPTION
**Pull request by Uruknara**
#### Description

Rework of all the french translation:

Added missing line and translate it
Translate wrong one
Correct all the orthographic and ponctuation fault
Sort out all the line

### CODE REVIEW

**Comment by Uruknara** [comment]
@Fallenbagel do you need something else to merge it ?

**Comment by Fallenbagel** [comment]
No I just need some time to review it

**Review by Showdown76py — APPROVED** [review]

**Review by Faywyrr — APPROVED** [review]

**Review by evandotsh — APPROVED** [review]

**Review by WizzardHub — APPROVED** [review]
A+

**Review by Poloin34 — APPROVED** [review]
LGTM

**Review by tarkalex — APPROVED** [review]

**Review by Haurus777 — APPROVED** [review]

**Comment by Fallenbagel** [comment]
@all-contributors please add @Gauvino for translation

**Pull request merged**
