### PR TITLE
refactor: updated german translations

### PR DESCRIPTION
**Pull request by Bretterteig**
#### Description
Updated German translations. Key points:
* Sort json object (equivalent to en.json)
* Added all missing translations
* Replaced Plex with {mediaServer} where applicable
* Removed **some** deprecated key where newer apply

#### To-Dos

- [ ] Successful build `yarn build`
- [ ] Translation keys `yarn i18n:extract`
- [ ] Database migration (if required)

### CODE REVIEW

**Review by gauthier-th — APPROVED** [review]
LGTM!

**Review by gauthier-th — APPROVED** [review]

**Review by Fallenbagel — COMMENTED** [review]
~Not to be pedantic or anything but this should be a, `refactor:` conventional commit message metadata tag rather than `feat:`~

Nvm commits aren't using the conventional commit messages

**Review by Fallenbagel — APPROVED** [review]

**Comment by Fallenbagel** [comment]
@all-contributors please add @Bretterteig for translation

**Pull request merged**
