### PR TITLE
Translation key fix for Jellyfin jobs

### PR DESCRIPTION
**Pull request by d-fendrich**
#### Description

The Jellyfin scan jobs translation keys did not match for some languages.
This pull request unifies these translation keys so that they are displayed correctly.

### CODE REVIEW

**Comment by Fallenbagel** [comment]
Could you resolve the merge conflicts?

**Comment by d-fendrich** [comment]
Conflicts resolved

**Review by Fallenbagel — APPROVED** [review]

**Comment by Fallenbagel** [comment]
@all-contributors please add @d-fendrich for translation

**Pull request merged**
