### PR TITLE
feat: added the `audienceRating` and `audienceScore` fields back to rating response

### PR DESCRIPTION
**Pull request by darmiel**
#### Description

Added the `audienceRating` and `audienceScore` fields back to rating response

#### Screenshots

|Before|After|
|---|---|
| image | image |

#### To-Dos

- [x] Successful build `yarn build`
- [x] Translation keys `yarn i18n:extract`
- [x] ~~Database migration (if required)~~

### CODE REVIEW

**Comment by Fallenbagel** [comment]
How wonder how this would go with #399

**Comment by Fallenbagel** [comment]
I'm not sure how we can approach this then 🤔

**Comment by darmiel** [comment]
> I'm not sure how we can approach this then 🤔 Any ideas?

This PR should not conflict with the other PR (only the file name changes in the other PR) in terms of functionality, so either

1) I wait until #399 is merged and change my PR accordingly (should only be the filename change)
2) This PR gets merged and the other PR pulls changes (if there are things you want the other PR to change anyways)
3) We close this PR and the changes can be added to the other PR (it's only a few lines anyways)

**Comment by Fallenbagel** [comment]
No no. I was talking about space. Cluttering. Like having 4 ratings on that small space

**Comment by darmiel** [comment]
Personally, I don't think this is too much clutter (yet):

image

**Comment by marcofaggian** [comment]
@darmiel @Fallenbagel I can add the changes to the other PR, two birds with one stone!

**Review by Fallenbagel — APPROVED** [review]

**Comment by Fallenbagel** [comment]
> @darmiel @Fallenbagel I can add the changes to the other PR, two birds with one stone!

You mean combine the two PRs?

**Comment by Fallenbagel** [comment]
Closing as #399 supersedes this.

**Pull request closed without merging**
