### PR TITLE
feat: add quality profile per user

### LINKED ISSUE #171: Defined root paths / quality profiles on a per-user basis
### Description

Currently with Ombi I'm able to set the default root path and quality/language profile on a per user basis. This allows for people who are not technically inclined to not have to worry about selecting a root folder or quality setting (and therefore I don't have to check they did it right every time they make a request). 

### Desired Behavior

Something like Ombi where quality profiles and root paths can be set both globally, but also on a per user basis. 

image

### Additional Context

_No response_

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

### LINKED ISSUE #419: [Feature Request] Possibility to specify Sonarr/Radarr root folder per user
### Description

I'd love to specify different root folders for different users.
Example:
Sonarr is configured with following root folders:
`/media/user1`
`/media/user2`
`/media/user3`

With Jellyfin, user1 has access to their personal library which is located at `/media/user1`.
The same goes for Jellyfin accounts user2 -> `/media/user2` and user3 -> `/media/user3`

Using Jellyseerr, there is indeed the possibility to grant users the permission `Advanced Requests` so they can manually choose the root folder where they want to have their downloaded content.

But sometimes - especially if those root folders are meant to be user-specific personal Jellyfin libraries - an option to specify one specific root folder would be very nice.
Because even if the users are aware that they have to change this value - eventually they might forget about it.

### Desired Behavior

One possibility to achieve that:
Add a possibility under _Settings_ -> _Services_ -> _Edit Radar/Sonarr_ -> _Root Folder_ to optionally add different root folders linked to one/several Jellyseerr users.

Another place where such an option could be integrated is, of course, _Settings_ -> _Users_, where a submenu could be added with the option to link Sonarr/Radarr root folders to one/several Jellyseerr users.

The same goes for _Users_ -> _user1_ -> _View Profile_ -> _Permissions_

I don't know how hard it is to implement such an option but one similar idea is probably #197

Thanks for all your hard work! 

### Additional Context

_No response_

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

### PR DESCRIPTION
**Pull request by gauthier-th**
#### Description

This PR adds options to define specific quality profiles per user. The quality profile sent to Radarr/Sonarr will be changed if the setting has been modified for the user making the request.

#### Screenshot (if UI-related)

Default values in the user settings, taken from the service option (4k option for Radarr/Sonarr also exists but is not showed here):
image

With a different quality profile for Radarr:
image

In the next request of the user, the quality profile on Radarr will be Bluray 1080p (unless the person that accepts the media request chooses another profile).

#### To-Dos

- [x] Successful build `yarn build`
- [x] Translation keys `yarn i18n:extract`
- [x] Database migration (if required)

#### Fixes
- Fixes #419 (partly)
- Fixes #171 (partly)

### CODE REVIEW

**Comment by feerlessleadr** [comment]
@gauthier-th really excited to see this PR. Does this also include the ability to set root folders per user as well?

**Comment by gauthier-th** [comment]
> @gauthier-th really excited to see this PR. Does this also include the ability to set root folders per user as well?

Not for now, this only includes the quality profiles per user.
It may be something we add on our roadmap @Fallenbagel? I don't know how much this is needed or asked.

**Comment by Fallenbagel** [comment]
> Not for now, this only includes the quality profiles per user.
> It may be something we add on our roadmap @Fallenbagel? I don't know how much this is needed or asked.

It's already in the road map. This pr accomplishes part of it. Then the rootfolder should accomplish a small part and the overriding rootfolder/profile depending on filter rules the rest

**Review by Fallenbagel — APPROVED** [review]

**Comment by gauthier-th** [comment]
This is closed in favor of #945

**Pull request closed without merging**
