### PR TITLE
fix: Length of undefined on users warnings

### PR DESCRIPTION
**Pull request by franciscofsales**
#### Description

On my instance, I was getting a frontend error where the were some issues with trying to check the length of undefined.
I tracked it down to a function that was not completely checking its dependencies and just added a more extensive check that should prevent this issue from happening again.

I didn't find anyone else with the same issue but regardless, this PR is a tiny improvement.

This PR does not change any functionality or affect any of the existing ones

#### Screenshot (if UI-related)

image

#### To-Dos
N/A

#### Issues Fixed or Closed
Could not find anyone experiencing the same issue.

### CODE REVIEW

**Comment by gauthier-th** [comment]
Could you tell use how to reproduce this issue?

**Comment by franciscofsales** [comment]
Sure, so I run it in the a kuberetes cluster and there's a custom ingress and error handler, this issue happens when the `/api/v1/auth/me` request does not return the expected 403 response and instead returns something else, which was my cause given that I run https://github.com/tarampampam/error-pages on my setup

**Review by gauthier-th — APPROVED** [review]
lgtm

**Comment by gauthier-th** [comment]
https://github.com/all-contributors please add @franciscofsales for code

**Comment by gauthier-th** [comment]
@all-contributors please add @franciscofsales for code

**Pull request merged**
