### PR TITLE
feat(notifications): improve discord notifications

### PR DESCRIPTION
**Pull request by guillaumearnx**
#### Description

Added a field in the general notification settings to allow a role to be mentioned in the webhook message via discord notification agent

#### Screenshot (if UI-related)

image
image

#### To-Dos

- [X] Successful build `pnpm build`
- [X] Translation keys `pnpm i18n:extract`
- [ ] Database migration (if required)

### CODE REVIEW

**Comment by guillaumearnx** [comment]
Done. but `pnpm i18n:extract` didn't change content of **en.json** file

**Review by gauthier-th — APPROVED** [review]
LGTM

**Review by Fallenbagel — APPROVED** [review]
Lgtm

**Comment by gauthier-th** [comment]
@all-contributors please add @guillaumearnx for code

**Comment by Fallenbagel** [comment]
@all-contributors please add @guillaumearnx for code

**Pull request merged**
