### PR TITLE
feat(watchlist): Add media to watchlist

### PR DESCRIPTION
**Pull request by yalagin**
feat(add watchlist): adding missing functionality from Overseerr

#### Description
Adding watchlist functionality to Jellyseerr
now it's on list view
#### Screenshot (if UI-related)
Screenshot 2023-04-27 at 22 33 51

#### To-Dos

- [ ]  add watchlist button to media page

### CODE REVIEW

**Comment by Fallenbagel** [comment]
Wait watchlist was missing? 🤔
I didnt realise though I have been merging from upstream to keep feature parity

**Comment by yalagin** [comment]
Well it's not missing it's not available for Jellyfin users. I want to bookmark some media for future downloads. In plex its called watchchlist. So I decided to add watchlist functionality to jellyseerr.

**Comment by Fallenbagel** [comment]
> Well it's not missing it's not available for Jellyfin users. I want to bookmark some media for future downloads. In plex its called watchchlist. So I decided to add watchlist functionality to jellyseerr. 

Wait how would watchlist work for jellyfin users? Won't they need a plex server?

**Comment by yalagin** [comment]
no they dont need plex server 
you can press star on media  
Screenshot 2023-04-28 at 00 49 10
it will add it to watchlist in database 
Screenshot 2023-04-28 at 00 50 37
you can press minus to delete media from watchlist
instead of loading it from plex server we will load it from database

**Comment by Fallenbagel** [comment]
> no they dont need plex server 
> you can press star on media  
> Screenshot 2023-04-28 at 00 49 10
> it will add it to watchlist in database 
> Screenshot 2023-04-28 at 00 50 37
> you can press minus to delete media from watchlist
> instead of loading it from plex server we will load it from sql database that jellyseerr using already
> 

OOO I LOVE THIS! Thank you so much for the PR! I'll review it soon. 2 tests seems to have failed I'll have a look at it tomorrow in the morning

**Review by Fallenbagel — APPROVED** [review]

**Review by Fallenbagel — APPROVED** [review]
Looks good to me!

**Comment by Codename-11** [comment]
How does one view the items added to the watchlist? I use Jellyfin, which I know doesn't have a watchlist functionality built in...

**Comment by Cavonzio** [comment]
> How does one view the items added to the watchlist? I use Jellyfin, which I know doesn't have a watchlist functionality built in...

They should add a watchlist menu in jellyseer, otherwise this is confusing for jellyfin users

**Comment by Fallenbagel** [comment]
> > How does one view the items added to the watchlist? I use Jellyfin, which I know doesn't have a watchlist functionality built in...
> 
> They should add a watchlist menu in jellyseer, otherwise this is confusing for jellyfin users

#527

you can now press `your watchlist` slider and expand to see all your watchlists. In addition, if the user has `View Watchlists` permission, they can see others watchlists from the profile (admin should be able to see everyones)

**Comment by Fallenbagel** [comment]
@all-contributors please add @yalagin for code

**Pull request merged**
