### PR TITLE
style: implement thin dark scrollbar for better UI consistency

### LINKED ISSUE #856: Scrollbar Look.
### Description

The default thick white scrollbar is not matching with the modern UI of jellyseerr, it would be nice if it was thin and matched the colors of the UI.
image

### Desired Behavior

it can be easily changed to something like this:
image

### Additional Context

For anyone who uses darkreader extension you can add the following CSS to make the scrollbar as shown above:

```
* {
  scrollbar-width: thin;
  scrollbar-color: #4b5563 #1f2937;
}

*:hover {
  scrollbar-color: #6b7280 #1f2937;
}
```

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

### PR DESCRIPTION
**Pull request by XDark187**
#### Description

Changed the scrollbar to be a thinner and darker to match the theme of jellyseerr.

#### Screenshot (if UI-related)
Before:
image

After:
image

#### To-Dos

- [x] Successful build `pnpm build`
- [ ] Translation keys `pnpm i18n:extract`
- [ ] Database migration (if required)

#### Issues Fixed or Closed

- Fixes #856

### CODE REVIEW

**Review by gauthier-th — APPROVED** [review]
LGTM!

**Comment by Fallenbagel** [comment]
@all-contributors please add @Bretterteig for code

**Comment by Fallenbagel** [comment]
@all-contributors please add @XDark187 for code

**Pull request merged**
